import { defineConfig } from "tsdown";

export default defineConfig([
  {
    entry: { index: "src/index.ts" },
    format: ["esm"],
    dts: true,
    outDir: "dist/esm",
    clean: true,
    sourcemap: true,
    platform: "node",
    target: "node20",
    hash: false,
    fixedExtension: true,
  },
  {
    entry: { index: "src/index.cjs.ts" },
    format: ["cjs"],
    dts: false,
    outDir: "dist/cjs",
    clean: false,
    sourcemap: true,
    platform: "node",
    target: "node20",
    hash: false,
    fixedExtension: true,
  },
  {
    entry: { bin: "src/bin.ts" },
    format: ["esm"],
    dts: false,
    outDir: "dist/esm",
    clean: false,
    sourcemap: true,
    platform: "node",
    target: "node20",
    hash: false,
    fixedExtension: true,
    inlineOnly: ["picocolors"],
    banner: "#!/usr/bin/env node\n",
  },
]);
