import { defineConfig } from "tsdown";

export default defineConfig([
  {
    entry: { index: "src/index.ts", detector: "src/detector/index.ts" },
    format: ["esm"],
    dts: true,
    outDir: "dist/esm",
    clean: true,
    platform: "node",
    target: "node22",
    hash: false,
    fixedExtension: true,
  },
  {
    entry: { index: "src/index.cjs.ts", detector: "src/detector/index.cjs.ts" },
    format: ["cjs"],
    dts: false,
    outDir: "dist/cjs",
    clean: false,
    platform: "node",
    target: "node22",
    hash: false,
    fixedExtension: true,
  },
  {
    entry: { bin: "src/bin.ts" },
    format: ["esm"],
    dts: false,
    outDir: "dist/esm",
    clean: false,
    platform: "node",
    target: "node22",
    hash: false,
    fixedExtension: true,
    deps: {
      onlyBundle: ["picocolors"],
    },
    banner: "#!/usr/bin/env node\n",
  },
  {
    entry: { "worker/count-worker": "src/cli/batch/jobs/worker/count-worker.ts" },
    format: ["esm"],
    dts: false,
    outDir: "dist/esm",
    clean: false,
    platform: "node",
    target: "node22",
    hash: false,
    fixedExtension: true,
  },
]);
